### ISSUE TITLE
[Feature] enable withPrefabValuesForField() for classes deeper down the object tree

### ISSUE THREAD

**Issue by Vankog** [jqno/equalsverifier#1017]
### Describe the feature

I have `A`, that contains `B` and a List of some sort.  
In `B` there is a cyclic dependency to `B` again (e.g. a List of sub-items).   
```java
class A {
    List<String> stringList;
    B b;
}

class B {
    List<B> subItems;
}
```

EquaslVerifier reports a cyclic error when running against A and B.

To resolve this, I can currently do:
* In the EqualsVerifier test of `B`, I can use both prefab methods to resolve the recursive error:
  * `withPrefabValues(List.class, red, blue)`
  * `withPrefabValuesForField("subItems", red, blue)`
* In the EqualsVerifier test of `A`, I can only use the original prefab method to resolve the recursive error:
  * `withPrefabValues(List.class, red, blue)`

Issues:  
* Using `withPrefabValuesForField("subItems", red, blue)` against `A` does not work, as the field does not exist there.
* Using `withPrefabValues(List.class, red, blue)` will probably also use the prefabs for `A.stringList`, which is not ideal. At least I assume this behavior. (to be clarified)

### Describe the solution you'd like

I'd like to use `withPrefabValuesForField("subItems", red, blue)` by providing the concrete class for the targeted field.   
e.g.  `withPrefabValuesForField(B.class, "subItems", red, blue)`

It might be helpful for `withPrefabValues()`as well. 
e.g. `withPrefabValues(B.class, List.class, red, blue)`

### Describe alternatives

For the issue of `withPrefabValues(List.class, red, blue)` possibly filling the wrong List:  
Is there a way to define the generics of the List as well?   
Maybe like Jackson ObjectMapper uses `TypeReference<List<B>>{}`

I know about `withGenericPrefabValues`, but to be honest, I don't really understand how to use it. The JavaDoc is a bit sparse. So if this solves this issue, my suggestion is, to improve the docs about this, especially with examples.

Hope this helps!
Thank you!

**Comment by jqno** [comment]
The intention of `withPrefabValuesForField()` is to only provide values for fields that are actually in the class under test. So when testing `A`, you could use it as `withPrefabValuesForField("stringList", List.of(new B()), List.of())` (for example), and you could use `withPrefabValuesForField("b", someB, anotherB)`. I won't add a way to make `withPrefabValuesForField` apply to any given field name somewhere in the hierarchy, because that would be very brittle. Some dependency could do a refactoring and suddenly your EqualsVerifier test might behave differently.

Your point about the sparse Javadoc is quite valid, I'll see about improving that. (I'll leave the ticket open until I do.)

In the mean time, you can also look here: https://jqno.nl/equalsverifier/errormessages/recursive-datastructure/#generics

**Comment by Vankog** [comment]
Yes, I saw this documentation. But I couldn't make much sense of it neither.   
As it is for Android, I don't have `SparseArray` easily available in my JDK for inspection and experimentation. Especially, I couldn't make sense about why providing the default constructor as a factory does help with the generics issue.  

I thought, that the factory should provide the actual values, matching the generic type. But this made not much sense, neither.   
So I'm a little lost about these two `withGeneric` methods.

Thus, I wasn't sure that and how it applies to the issue.

What happens if I use 
`withPrefabValues(List.class, listWithStrings1, listWithStrings2)`
against a class with 
```java
List<String> stringList;
List<Integer> integerList;
```

Does EqualsVerifier provide the Strings to the Integer list as well? Or does EqualsVerifier realizes, that the prefab values are of type String and uses the normal value provider for the integerList?

**Comment by jqno** [comment]
The reason for having `withGenericPrefabValues` is when you class has a field of a generic type, and this generic type declares a variable of this generic type _in its equals or hashCode method_ and assigns its generic value to that variable. It's pretty rare, and the only real-life case I've found (outside of proprietary code bases) was Android's SparseArray, so that's why that's the example. A SparseArray is a List (I'm not sure if it implements java.util.List, but it does behave like it), and its equals method looks kind of like this:
```java
private final List<T> values;

public boolean equals(Object obj) {
    // ...
    SparseArray other = (SparseArray)obj;
    for (int i = 0; i <= values.size(), i++) {
        T thisValue = values.get(i); // note: implicit cast because of generics
        T otherValue = other.values.get(i); // another implicit cast
        if (!thisValue.equals(otherValue) return false;
    }
}
```
(I'm doing this from memory so it probably looks different, but you get the idea)

Your example with `List<String>` and `List<Integer>` is also a good use case for `withGenericPrefabValues`, because indeed, if you do a `withPrefabValues(List.class, strings1, strings2)`, it will use the string lists for the integer list as well.

So in that situation, you could do this:

```java
EqualsVerifier.forClass(...)
    .withGenericPrefabValues(List.class, value -> List.of(value)
    .verify();
```

EqualsVerifier will provide a value of the correct type, and you can use it to construct your class (in this case a List).

EqualsVerifier already has this example built-in for List, because List is so common. But if you were to build something yourself, this is how you would use it.

I haven't been able to come up yet with a way to formulate this wall of text in a way that fits easily into a javadoc comment that people would want to read, but I'll keep thinking, and when I have something I'll update it.

This is a very long-winded way to say that in the specific example in your original question, `withGenericPrefabValues` isn't going to help you. I'd just use `.withPrefabValues(B.class, someB, anotherB)`.

**Comment by Vankog** [comment]
Now I finally got it. EqualsVerifier provides the values of type `T`. And in `withGenericPrefabValues()` you have to provide a factory for the holder of `T` to pass the `T` value to. So the `SparseArray::new` of the Javadoc is not the default constructor as I thought, but the 1 param constructor, accepting the value.  
Thanks for the clarification.  
Maybe I can come up with something as well.

**Comment by jqno** [comment]
That's exactly right. Based on that, I've made a small update in the docs: https://jqno.nl/equalsverifier/errormessages/recursive-datastructure/

Instead of using `SparseArray::new`, I wrote `element -> new SparseArray(element)`. By writing out the lambda parameter, I think it's a little clearer.

I'll make other improvements if and when they come up...
