### ISSUE TITLE
[Bug] Class file for `SuppressFBWarnings` not found updating to 3.17.4

### ISSUE THREAD

**Issue by jack-berg** [jqno/equalsverifier#1026]
### Describe the bug

When [updating from 3.17.3 to 3.17.4](https://github.com/open-telemetry/opentelemetry-java/pull/6912), we encounter the following error:

```
/Users/jberg/.gradle/caches/modules-2/files-2.1/nl.jqno.equalsverifier/equalsverifier/3.17.4/7b177b71a5ebf2b65956590f7a1a932348f82662/equalsverifier-3.17.4.jar(/nl/jqno/equalsverifier/api/SingleTypeEqualsVerifierApi.class): warning: Cannot find annotation method 'value()' in type 'SuppressFBWarnings': class file for edu.umd.cs.findbugs.annotations.SuppressFBWarnings not found
```

See example from github actions [here](https://github.com/open-telemetry/opentelemetry-java/actions/runs/12087344035/job/33708584865?pr=6912).

Appears related to this recent commit: https://github.com/jqno/equalsverifier/commit/823b9cb791369d5002fdb067d81d4f0622fc05d9

I [fixed](https://github.com/open-telemetry/opentelemetry-java/pull/6912/commits/c20dfe1b6785aa4c0af72dbf114a1e0150b41977) by including a dependency on `com.google.code.findbugs:annotations:3.0.1`, but seems strange to have to bring this dependency myself, and for this change to occur in a patch release. 

Is this expected?

**Comment by jqno** [comment]
Thanks for letting me know, this is definitely not supposed to happen. I'll look into it!

**Comment by jqno** [comment]
Sorry it took a while, but version 3.17.5 is now syncing with Maven Central.

I don't undestand 100% what the problem was, but I'll try to explain anyway. I use Spotbugs internally, and sometimes I need to suppress a warning. Spotbugs provides the `@SuppressFBWarnings` annotation for that, which has a retention type of `CLASS`, which means it's present in the class file but normally a client wouldn't need the dependency.

What changed in 3.17.4, is that now, the annotation was placed in a class that client code directly interacts with (even if it's not imported by the client code: it's a return type halfway a fluent API interface). Normally you still shouldn't have to have the dependency, but I think the problem is that you're using a build plugin that does annotation processing. I haven't been able to identify which one specifically; it might have been ErrorProne. For certain kinds of annotation processing, the dependency _is_ needed, apparently.

I've solved it by reverting a refactoring so the annotation isn't on a class in the fluent API anymore, and also I've created my own `@SuppressFBWarnings` annotation. Apparently, SpotBugs accepts that too, and it has the advantage that you don't need an external dependency anymore, so even in future refactorings, we should still be safe.

**Comment by nvervelle** [comment]
Hi @jqno 

I see the same issue as @jack-berg . We are indeed using annotation processing and errorprone.

**Comment by jqno** [comment]
It's nice to see that confirmation. Please let me know if the new release fixes the problem for you!

**Comment by eorloff** [comment]
@jqno We have experienced the same problem in a lot of our projects, but are encountering the problem both when running with errorprone and when running without. We are running with `-Xlint:all' which might be what causes the problem. I have found this bug on the JDK that seems to highlight the same problem: https://bugs.openjdk.org/browse/JDK-8342833

Thanks for the rapid fix - as soon as it is available on maven central I will check if it resolves the problem.

**Comment by nvervelle** [comment]
I've retrieved the new version, it's currently building in CI, I will keep you posted.

**Comment by nvervelle** [comment]
Build went through :tada: 

Thanks !

**Comment by jqno** [comment]
Nice! Glad to hear!
