### ISSUE TITLE
Significant fields: hashCode relies on trade, but equals does not.

### ISSUE THREAD

**Issue by haribabusapa** [jqno/equalsverifier#117]
Hi , 
We are facing below error when we are executing Test case for my project.
We couldn't get the solution from Equalsverifier/errormessages. Kindly help us in resolving this.

java.lang.AssertionError: Significant fields: hashCode relies on trade, but equals does not.

// Thanks

**Comment by jqno** [comment]
Hi,

According to the hashCode contract, if two objects are equal to each other, their hashCodes must be too. In your case, apparently, if you change the value of the 'trade' field, the hashCode will change, but equals will not. That means that either your hashCode method or your equals method is incorrect.

Jan

**Comment by haribabusapa** [comment]
Hi,
Thank you for quick reply. But, we are using Lombok(@Data) to generate equals and hashcode methods automatically. Kindly suggest in this scenario. 

//Thanks

**Comment by jqno** [comment]
Hi,
That's interesting, I do test EqualsVerifier with Lombok.
Can you send me some code that reproduces this problem? Also, which version are you using of EqualsVerifier and Lombok?

Jan

**Comment by haribabusapa** [comment]
Hi,
We are using below versions
lombok:1.14.8 and  equalsverifier:1.6 

Sample code \

Class TestClass extends Specifications {
@Test
@Unroll

def 'Test #testClass' () {
  expect:
   EqualsVerifier.forClass(testClass) 
   .withPrefabValues (Tsn ,new Tsn(id :1) , new Tsn(id :2 ))
    .withPrefabValues (TsnVrs ,new TsnVrs(id :1) , new TsnVrs(id :2 ))  
     .suppress (Warning.NONFINAL_FIELDS).verify()

where:
 testClass |_
 ExampleClass|_
}
}

@Data

public final class ExampleClass{
private Trade trade;
private Tsn present;
private TsnVrs presentTsnVrs;
private Optional<Tsn> previous;
private Tsn returnValue;

public ExampleClass (Trade trade){
this.trade = trade;
this.present = trade.getTsn();
this.presentTsnVrs = trade.getPresentTsnVrs();
}
}

Note :   Trade is an Abstract class which  has Tsn and TsnVrs as member variables.

// Thanks

**Comment by jqno** [comment]
Hi,
Thanks for posting that, but I was looking more for something that I can simply copy paste into my IDE so I can start debugging directly. I don't know what those Trade, Tsn, TsnVrs, and Optional classes look like. (Is that a class you defined, or is it Java 8's optional? If the latter, why isn't it a raw type?) And I don't even know what language that unit test is written in... (Is it Groovy?) I'd have to make way too many assumptions, and spend a lot of time, in order to find the issue, and I'm not even certain I would be able to find it this way.

Can you please post something that's self-contained? For instance, can you boil it down to one or two, maybe three, complete Java classes that don't depend on anything outside of Java itself (and Lombok, obviously) so I can copy/paste it to my IDE? If that's not possible, can you create a zip file containing a small Maven project (or Gradle, if it was indeed Groovy :) ) that reproduces the problem?

Thanks!
Jan

**Comment by jqno** [comment]
It's been a while, did you manage to find something more self-contained that reproduces this? If not, I'll probably close this issue later.

**Comment by haribabusapa** [comment]
Thank you You can close this.

Regards
Hari

**Comment by jqno** [comment]
Ok. Thanks for the update.
