### ISSUE TITLE
Suppress - Overloaded: More than one equals method found

### ISSUE THREAD

**Issue by ZPetrovich** [jqno/equalsverifier#127]
Hello,

I would like to have possibility to avoid throw _java.lang.AssertionError: Overloaded: More than one equals method found._ when it is makes sense to have overloaded equals method.

Please see my example

``` java
import nl.jqno.equalsverifier.EqualsVerifier;

import org.junit.Test;

public class VerifyOverloadFailed {
    class Thing {
        final int x;

        Thing(int x) {
            this.x = x;
        }

        @Override
        public int hashCode() {
            return x;
        }

        public boolean equals(Thing other) {
            return this.x == other.x;
        }

        @Override
        public boolean equals(Object o) {
            return (o instanceof Thing) && (this.equals((Thing) o));
        }
    }

    @Test
    public void testEquals() {
        EqualsVerifier.forClass(Thing.class).verify();
    }
}
```

Thanks!

**Comment by jqno** [comment]
Thanks for reporting this.

I've actually considered this before, but there's one question I can't really answer, and that is: what does the overload really bring? Java has no generic `Equatable` interface like C# has. Due to type erasure, collections will never call the overload. And even if they did, no matter what you do, you'll always have to write the `Object` overload with the type check and the cast. And if you do, why not have that method handle the case when it's a `Thing`? The only thing I can figure, is that it's a performance thing, but I've never seen any profiler data saying that it actually matters.

I'd be very interested to have an answer to this. If you can convince me, I'll add it to EqualsVerifier :).

**Comment by ZPetrovich** [comment]
Well, my argument is simple. We have a source code which we can't modify but need to cover it with tests. Without this thing I need to create so much tests manually. So it may be added as an _option_ to EqualsVerifier if you in doubt regarding overall Language Design Philosophy.

Thanks!

**Comment by jqno** [comment]
OK, I feel your pain there :(.
But I still think it's not a good idea in general to do this, even though it's obviously outside of your control. I don't want to add options to EqualsVerifer for things that I don't agree with, because I also have to support them in the future. I do this in my free time, and I can't do everything that people request. So I'm not going to add this option.
Of course you're free to for EqualsVerifier and add the option yourself. If you want, I'll point you to where you can do that in the code.

Good luck,
Jan

**Comment by ZPetrovich** [comment]
OK, many thanks for your feedback! I understand and appreciate your time! 
I do not think I'll be able to fix it by myself, build locally and integrate to the project. Wanna use only stable libraries in our project.
Maybe we will have ability to change source code soon so this will be fixed by itself.

Also could you pls point me on some book/article where they say that overloading _equals_ is not the best idea?

Thanks!

**Comment by shelley-jean-baker** [comment]
I have a class that provides a `static` `equals` method that takes multiple parameters, and EqualsVerifier fails with the same error: `java.lang.AssertionError: Overloaded: More than one equals method found`.

Would it be possible to reopen this issue to allow suppressing _static_ equals methods?

**Comment by jqno** [comment]
Hi!
Sorry for the late reply, I was on vacation.
I think your case with a static equals method would cause less confusion than OP's case. On the other hand, is there a reason why you can't simply rename the static equals method, like the OP had?
