### ISSUE TITLE
Recursive datastructure error with HashMap class

### ISSUE THREAD

**Issue by shollander** [jqno/equalsverifier#146]
# What steps will reproduce the problem?
# What is the code that triggers this problem?

```
EqualsVerifier.forClass(MyClass.class)
    .suppress(Warning.STRICT_INHERITANCE, Warning.NON_FINAL_FIELDS)
    .verify();
```

Please try to provide an example of a complete class (equals method, hashCode method, relevant fields) and a call to EqualsVerifier.

Where my MyClass.java is a simple class:

```
public class MyClass {
    String string;
    MyMap myMap;

    public String getString() {
        return string;
    }
    public void setString(String string) {
        this.string = string;
    }
    public MyMap getMyMap() {
        return myMap;
    }
    public void setMyMap(MyMap myMap) {
        this.myMap = myMap;
    }
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((myMap == null) ? 0 : myMap.hashCode());
        result = prime * result + ((string == null) ? 0 : string.hashCode());
        return result;
    }
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (!(obj instanceof MyClass)) {
            return false;
        }
        MyClass other = (MyClass) obj;
        if (myMap == null) {
            if (other.myMap != null) {
                return false;
            }
        } else if (!myMap.equals(other.myMap)) {
            return false;
        }
        if (string == null) {
            if (other.string != null) {
                return false;
            }
        } else if (!string.equals(other.string)) {
            return false;
        }
        return true;
    }
    @Override
    public String toString() {
        return "MyClass [string=" + string + ", myMap=" + myMap + "]";
    }

}
```

And this is MyMap.java:

```
import java.util.HashMap;

public final class MyMap extends HashMap<String, Object> {

    private static final long serialVersionUID = 1036030120615821348L;

}
```
# What error message or stack trace does EqualsVerifier give?

Recursive datastructure
# What did you expect?

No error
# Which version of EqualsVerifier are you using?

2.1
# Please provide any additional information below.

**Comment by jqno** [comment]
This happens because `HashMap` is a recursive datastructure, and `MyMap` inherits from it. If you look at the source of `HashMap`, you'll notice it has a field `Node<K,V>[] table`. `Node` is a type that's defined inside `HashMap`, and that has a field `Node<K,V> next`, which is where the recursion comes from.

EqualsVerifier has to create instances of all types it encounters in order to do its job, but it can't instantiate types that are recursively defined, like this one.

Apart from saying "recursive datastructure", EqualsVerifier gives you a list of types that cause this recursion. You have to make instances of one of these types and give them to EqualsVerifier using the `withPrefabValues` method. In your case, I recommend `MyMap`:

```
    MyMap red = new MyMap();
    red.put("a", "b");
    MyMap black = new MyMap();
    black.put("x", "y");
    EqualsVerifier.forClass(MyClass.class)
            .suppress(Warning.STRICT_INHERITANCE, Warning.NONFINAL_FIELDS)
            .withPrefabValues(MyMap.class, red, black)
            .verify();
```

Obviously, because `HashMap` is always available and frequently used, EqualsVerifier already has pre-made instances of that in its prefab value list. But that doesn't help with `MyMap`, because of the inheritance relation. You can't take a `HashMap` object and pretend it's a `MyMap`.

**Comment by shollander** [comment]
Ok that makes sense. Thanks for the explanation. I knew that regular maps
worked, so I wasn't sure why I was getting that error.

It would be nice if there was some way to not have to deal with the prefab
values, but it doesn't look like there is.

**Comment by jqno** [comment]
Indeed, I haven't found one yet, unfortunately.
