### ISSUE TITLE
Unexpected "Significant fields: equals does not use (field), or it is stateless" for atypical handling of the field

### ISSUE THREAD

**Issue by dukeyin** [jqno/equalsverifier#160]
I'm trying to use EqualsVerifier 2.1.6.  I have an object that stores serialized JSON in `String` fields (not my favorite design choice, but it is what it is). Because of that, there are custom implementations of `equals` and `hashCode` which call methods which deserialize these `String` fields into `Map` values.

e.g.,

```
public class MyObject {
    private String Name;
    @SerializedJsonMap private String Additional;

    public Map<String, Object> getAdditionalMap() throws RuntimeException
    {
        Map<String, Object> map = new HashMap<>();
        if(Additional != null)
        {
            try
            {
                map = MyJacksonObjectMapper.get().readValue(Additional, HashMap.class);
            }
            catch(IOException e)
            {
                throw new RuntimeException(e);
            }
        }
        return map;
    }

    public boolean equals(Object obj)
    {
        if(obj == null || !(obj instanceof MyObject))
        {
            return false;
        }

        MyObject that = (MyObject) obj;

        return Objects.equals(this.Name, that.Name)
                && Objects.equals(this.getAdditionalMap(), that.getAdditionalMap());
    }

    public int hashCode()
    {
        return Objects.hash(
                this.Name,
                this.getAdditionalMap());
    }
}
```

As a first attempt at EqualsVerifier, I tried:

```
EqualsVerifier.forClass(MyObject.class)
        .suppress(Warning.STRICT_INHERITANCE)
        .suppress(Warning.NONFINAL_FIELDS)
        .withPrefabValues(String.class, "{}", "{\"someValue\":21}}")
        .verify();
```

but this yields:

```
java.lang.AssertionError: Significant fields: equals does not use Additional, or it is stateless.
For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
    at nl.jqno.equalsverifier.EqualsVerifier.handleError(EqualsVerifier.java:381)
    at nl.jqno.equalsverifier.EqualsVerifier.verify(EqualsVerifier.java:367)
    at 
```

As far as I could tell, the only way I would be able to use EqualsVerifier would be to add in `.withIgnoredFields("Additional")`.  I guess this kind of pattern is pretty niche, but is it feasible to support objects that do things like this?

**Comment by jqno** [comment]
Thanks for reporting this. I'm currently on vacation, but I'll look into
this when I get back and I'll let you know.

**Comment by jqno** [comment]
I took a look, but unfortunately, I can't reproduce the problem. As far as I can see, this code should work.

I would expect the "significant fields" error to occur if `Additional` wasn't referenced in `equals` and `hashCode`, but it is, through the `getAdditionalMap` method. I'm not familiar with your JSON parser, so I changed your implementation like this:

```
public final class MyObject {
    private String Name;
    private int Additional;

    public String getAdditionalString() {
        return Integer.toString(Additional);
    }

    public boolean equals(Object obj)
    {
        if(obj == null || !(obj instanceof MyObject))
        {
            return false;
        }

        MyObject that = (MyObject) obj;

        return Objects.equals(this.Name, that.Name)
                && Objects.equals(this.getAdditionalString(), that.getAdditionalString());
    }

    public int hashCode()
    {
        return Objects.hash(
                this.Name,
                this.getAdditionalString());
    }
}
```

And this actually runs fine.

It can't be that you get an `IOException` every time for some reason either, because then the error would be different.

Would you be willing to fork [this repo](https://github.com/jqno/equalsverifier-issuerepro) and add your class in there, including whatever you need to get the JSON to work? Then I can look into it more closely and hopefully figure out why your code doesn't work.

**Comment by dukeyin** [comment]
I recently investigated this again.  (Sorry for the late response.)

I can still reproduce the original error report, but I have also discovered how to get the test to pass.

The original report had this code causing the significant fields assertion error:
```
public Map<String, Object> getAdditionalMap() throws RuntimeException
{
	Map<String, Object> map = new HashMap<>();
	if(Additional != null)
	{
		try
		{
			map = MyJacksonObjectMapper.get().readValue(Additional, HashMap.class);
		}
		catch(IOException e)
		{
			throw new RuntimeException(e);
		}
	}
	return map;
}
```

If I change the code like below, then the test starts passing(!):
```
public Map<String, Object> getAdditionalMap() throws RuntimeException
{
	if(Additional != null)
	{
		Map<String, Object> map = new HashMap<>();
		try
		{
			map = MyJacksonObjectMapper.get().readValue(Additional, HashMap.class);
		}
		catch(IOException e)
		{
			throw new RuntimeException(e);
		}
		return map;
	}
	return null;
}
```

The difference in the code that passes is that if the String is null, then the method would also return null.  (In the code that fails, if the String is null, then the method would return a non-null, empty Map.)  (However, this change isn't something I'd like to do.)

**Comment by jqno** [comment]
Hi,

Thanks for the update.

`getAdditionalMap` basically changes the "null-ness" of the field. I mean, if `Additional` would be null, the thing that actually gets compared in `equals` would not be. This might mess with EqualsVerifier's expectations. (Although when I replace the line `map = MyJacksonObjectMapper.get().readValue(Additional, HashMap.class);` with `map.put(Additional, 'x');`, EqualsVerifier just passes, so there must be something else going on, too.)

As a workaround for your problem, you could try suppressing `Warning.NONNULL_FIELDS`, or adding a @NonNull or @NotNull annotation to `Additional`. (EqualsVerifier supports these annotations from all providers, you could even create your own.)

However, I can't be certain that that will actually work because unfortunately, I still can't reproduce it myself; I would need to have your `MyJacksonObjectMapper` class, perhaps your `@SerializedJsonMap` annotation, and the classes they depend on. (I'm not sure if they're from some library that you use, or if they're custom to your project.)

If you send me something I can compile, I can look into it more thoroughly, if you want. A good starting point would be to fork the [issue repro](https://github.com/jqno/equalsverifier-issuerepro) repository.

**Comment by rogelio-blanco** [comment]
Hi, thanks for the hard work.   I was able to reproduce it by excluding a property from the equals, hashcode and to string function using lombok.

Sample code:

```
@Data
@NoArgsConstructor
@EqualsAndHashCode(exclude =
{ "parents" })
@ToString(exclude =
{ "parents" })
public class GHCommit implements Serializable {
    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

    private GHCommitUser author;
    private GHCommitUser committer;
    private int commentCount;
    private List<GHCommit> parents;
    private String message;
    private String sha;
    private String url;
    private GHTree tree;
}
```

**Comment by jqno** [comment]
It's the same error message, but it doesn't look like @dukeyin 's problem. In your case, you have explicitly excluded a field, and you need to tell EqualsVerifier about it using `withIgnoredFields`. See http://jqno.nl/equalsverifier/manual/ignoring-fields/ for more info.

In the original problem, the error seems to have a very different cause. @dukeyin, if you're still interested in figuring this out, please let me know. Otherwise I'll probably close this issue in a few days, to clean up.

**Comment by jqno** [comment]
(BTW, of course you can always reopen it, or open a new one, if you want to come back to this later!)

**Comment by dukeyin** [comment]
@jqno I am not actively looking into this, so feel free to tidy up your project!

**Comment by jqno** [comment]
Thanks!
