### ISSUE TITLE
Java 9/10 illegal reflective access to field java.lang.Thread.name

### ISSUE THREAD

**Issue by ekoutanov** [jqno/equalsverifier#193]
Another one for the reflective access gods...

# What steps will reproduce the problem?
Run EV on a class that encapsulates `java.lang.Thread` on JDK 10.

# What is the code that triggers this problem?
```java
public final class EqualsVerifierThreadTest {
  private static final class ThreadHolder {
    private final Thread thread;

    @SuppressWarnings("unused")
    ThreadHolder(Thread thread) {
      this.thread = thread;
    }
    
    @Override public boolean equals(Object obj) {
      if (this == obj) {
        return true;
      } else if (obj instanceof ThreadHolder) {
        final ThreadHolder that = (ThreadHolder) obj;
        return Objects.equals(thread, that.thread);
      } else {
        return false;
      }
    }
    
    @Override public int hashCode() {
      return Objects.hashCode(thread);
    }
  }
  
  @Test
  public void test() {
    EqualsVerifier.forClass(ThreadHolder.class)
    .withPrefabValues(Thread.class, new Thread("red"), new Thread("black")).verify();
  }
}
```

# What error message or stack trace does EqualsVerifier give?
Test passes. Javac (run from Gradle 4.6) prints following warning:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by nl.jqno.equalsverifier.internal.reflection.FieldAccessor (file:/Users/emil/.gradle/caches/modules-2/files-2.1/nl.jqno.equalsverifier/equalsverifier/2.4.6/e4a370639189cb7d6eb80d0763bac1b15ed227b/equalsverifier-2.4.6.jar) to field java.lang.Thread.name
WARNING: Please consider reporting this to the maintainers of nl.jqno.equalsverifier.internal.reflection.FieldAccessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```

# What did you expect?
No warning.

# Which version of EqualsVerifier are you using?
2.4.6

**Comment by jqno** [comment]
Thanks, nice catch!
I'll release the fix for this in the next version. I'll let you know when that happens.

**Comment by ekoutanov** [comment]
Thanks, and no rush.

**Comment by jqno** [comment]
I (finally 😉) released version 2.4.7, which fixes this.

**Comment by ekoutanov** [comment]
Thanks for the heads up @jqno . I ran it on a couple of projects just then and no problems spotted.

**Comment by jqno** [comment]
Thanks for testing it!

**Comment by bartosz-bilicki** [comment]
there is still warning when using version 3.19 with java 11 (test is passing)

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by nl.jqno.equalsverifier.internal.reflection.FieldAccessor (file:/../.gradle/caches/modules-2/files-2.1/nl.jqno.equalsverifier/equalsverifier/3.1.9/2f8586638e8c169da544466ad89d6eea8ea379b4/equalsverifier-3.1.9.jar) to field java.util.concurrent.atomic.AtomicReference.value
WARNING: Please consider reporting this to the maintainers of nl.jqno.equalsverifier.internal.reflection.FieldAccessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```

My code

```
@Test
    void equalsContract() {
        EqualsVerifier.forClass(MySlass.class)
                .withPrefabValues(AtomicReference.class,
                        new AtomicReference<>(...),
                        new AtomicReference<>(..)
                .verify();
    }
```

**Comment by jqno** [comment]
Hi,

It works fine for me. There's also a test for AtomicReference in
EqualsVerifier's test suite.
If you want me to look into it, you have to help me reproduce this --
perhaps by forking https://github.com/jqno/equalsverifier-issuerepro/


Regards,
Jan



On 10 September 2019 at 17:15:57, bartosz-bilicki (notifications@github.com)
wrote:

still occurs in version 3.19

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by
nl.jqno.equalsverifier.internal.reflection.FieldAccessor
(file:/../.gradle/caches/modules-2/files-2.1/nl.jqno.equalsverifier/equalsverifier/3.1.9/2f8586638e8c169da544466ad89d6eea8ea379b4/equalsverifier-3.1.9.jar)
to field java.util.concurrent.atomic.AtomicReference.value
WARNING: Please consider reporting this to the maintainers of
nl.jqno.equalsverifier.internal.reflection.FieldAccessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal
reflective access operations
WARNING: All illegal access operations will be denied in a future release

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jqno/equalsverifier/issues/193?email_source=notifications&email_token=AAGSRMI4WIOXN2I4G3RPR5TQI6223A5CNFSM4E5ONZZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6LO2VY#issuecomment-529984855>,
or mute the thread
