### ISSUE TITLE
JPA: Autodetect redefined superclass

### ISSUE THREAD

**Issue by xenoterracide** [jqno/equalsverifier#220]
```

@MappedSuperclass
public class AbstractEntityBase<SELF extends AbstractEntityBase<?>> 
```

```
@Entity( name = "emr_secure" )
public class Emr extends AbstractEntityBase<Emr> {
```

I feel like when doing

```
        EqualsVerifier.forClass( Emr.class )
                .withRedefinedSuperclass()
                .withOnlyTheseFields( "id" )
                .verify();
```

` .withRedefinedSuperclass()` could have been figured out on its own

**Comment by jqno** [comment]
That's probably true, but this is intentional.

Mixing inheritance and equals is a minefield, where a lot of bugs can occur if you're not careful. `.withRedefinedSuperclass()` is there so that people who read the code later, know that inheritance and equals are being mixed. And it's also there so that the author of the code knows he needs to pay extra special attention -- and perhaps think twice about actually going down this path.
