### ISSUE TITLE
Feature request: option to get instances from public constructors and static fields

### ISSUE THREAD

**Issue by Pr0methean** [jqno/equalsverifier#317]
There doesn't seem to be a way to properly configure EqualsVerifier to deal with a former singleton class that preserves the identity of its default instance through round-trip serialization. An example follows:
```
@ParametersAreNonnullByDefault
public class SecureRandomSeedGenerator implements Serializable {
  public static final SecureRandomSeedGenerator DEFAULT_INSTANCE
      = new SecureRandomSeedGenerator(new SecureRandom(), true);
  private static final long serialVersionUID = 854226000048040387L;
  private final SecureRandom source;
  private final boolean isDefaultInstance;

  public SecureRandomSeedGenerator(SecureRandom source) {
    this(source, false);
  }

  private SecureRandomSeedGenerator(SecureRandom source, boolean isDefaultInstance) {
    this.source = source;
    this.isDefaultInstance = isDefaultInstance;
  }

  protected Object readResolve() {
    return isDefaultInstance ? DEFAULT_INSTANCE : this;
  }

  @Override public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecureRandomSeedGenerator that = (SecureRandomSeedGenerator) o;
    return isDefaultInstance == that.isDefaultInstance && source.equals(that.source);
  }

  @Override public int hashCode() {
    // Using Integer.MAX_VALUE for default instance makes collisions less likely, since on some VMs
    // System.identityHashCode() always returns a value in a narrower range close to zero.
    return isDefaultInstance ? Integer.MAX_VALUE : source.hashCode();
  }
}
```
Notice that `x.isDefaultInstance` if and only if `x == DEFAULT_INSTANCE`. A proper test of `equals` would include `DEFAULT_INSTANCE` and instances created using the public constructor. Thus, it would be useful if EqualsVerifier had a mode which used the class's static fields and non-private constructors, or a provided list of Supplier<SecureRandomSeedGenerator>s, to create instances.

**Comment by jqno** [comment]
I see what you mean. However, in what way would this affect the way EqualsVerifier works? Can you show me a test that fails because of this?

The reason I ask, is that EqualsVerifier used to have this feature until version 2.0, where it was removed. The reason is that EqualsVerifier needs to reflectively change instances anyway, whether you provide instances or not. For example, it iterates over all the fields, changing them one by one, to see if something changes. This would include the `isDefaultInstance` field in your `DEFAULT_INSTANCE` constant. Because of this, the feature provided no real benefit while confusing users (people opened lots of tickets, that were often easily solved simply by not using that feature).

BTW, there is still the `forRelaxedEqualExamples()` method -- maybe this can help you in some way, too?

**Comment by Pr0methean** [comment]
Thanks! `forRelaxedEqualExamples` doesn't quite work, because it requires two "equal but not identical" instances (and the only way to produce any is to set `isDefaultInstance` to true reflectively on an instance other than DEFAULT_INSTANCE). I've also tried making `isDefaultInstance` an ignored field (since `DEFAULT_INSTANCE.source` is inaccessible when constructing any other instance), but this fails due to the shortcut in hashCode().

I'm looking into whether `isDefaultInstance` can be eliminated altogether, but this doesn't seem to be possible without breaking deserialization. (`DEFAULT_INSTANCE`, and only `DEFAULT_INSTANCE`, has its identity preserved through round-trip serialization, because the class was formerly a singleton enum.) Writing `this == DEFAULT_INSTANCE` to the ObjectOutputStream doesn't work, because `readObject` and `readExternal` can't replace the object and `readResolve` doesn't have access to the ObjectInputStream.

**Comment by jqno** [comment]
I still don't quite understand the problem. I realise that EqualsVerifier doesn't use the actual `DEFAULT_INSTANCE` in its verification, but how does that affect the `equals` checks?

The way I see it, the fact that `isDefaultInstance` can only be true with the former singleton instance, is an invariant that you have to test yourself (and you probably do), but it doesn't affect whether the `equals` method follows the `equals` contract as described in je `java.lang.Object` javadoc, which is EqualsVerifier's job.

Or do you have a specific EqualsVerifier test that fails when it should succeed, or the other way round?

**Comment by Pr0methean** [comment]
> The way I see it, the fact that `isDefaultInstance` can only be true with the former singleton instance, is an invariant that you have to test yourself (and you probably do), but it doesn't affect whether the `equals` method follows the `equals` contract as described in je `java.lang.Object` javadoc, which is EqualsVerifier's job.

Right, but my implementation of `equals` and `hashCode` relies on that invariant, and EqualsVerifier insists on breaking the invariant by mutating `isDefaultInstance` reflectively.

**Comment by jqno** [comment]
Indeed, EqualsVerifier breaks invariants. Unfortunately, that's part of the way it works, and can't be changed without a complete re-write.

Since you haven't shown me a failing test, I've run your class through EqualsVerifier, and the only real problem I found was that `equals` relies on `source` while `hashCode` does not. Is that what you mean when you say that your `equals` and `hashCode` implementations rely on the invariant? Becuase you can work around that problem by suppressing `Warning.STRICT_HASHCODE`.

I know that it seems wrong, but EqualsVerifier can still thoroughly check your `equals` and `hashCode` implementations, even while breaking an invariant or two along the way. Your class's `equals` method is not that different from "regular" `equals` methods that it couldn't do that.

I'm closing this issue now, but feel free to re-open if you can show me a failing EqualsVerifier test on your class.
