### ISSUE TITLE
Verify abstract class with private subclasses (com.google.common.hash.HashCode)

### ISSUE THREAD

**Issue by LukasGasior1** [jqno/equalsverifier#353]
# What steps will reproduce the problem?
Running a test agains this class: com.google.common.hash.HashCode or any class that uses it in its equals/hashCode methods.

# What is the code that triggers this problem?
`EqualsVerifier.forClass(HashCode.class).verify();`

# Provide an example of a complete class (equals method, hashCode method, relevant fields) and a call to EqualsVerifier.
It's here: https://github.com/google/guava/blob/master/guava/src/com/google/common/hash/HashCode.java

Remember, you have the problem right in front of you. I have to try and reproduce it in my spare time. Please help me, so that I can help you!

# What error message or stack trace does EqualsVerifier give?
`EqualsVerifier found a problem in class com.google.common.hash.HashCode.
-> Abstract delegation: HashCode's equals method delegates to an abstract method:
 Receiver class com.google.common.hash.HashCode$$DynamicSubclass$2126587552 does not define or inherit an implementation of the resolved method abstract bits()I of abstract class com.google.common.hash.HashCode.`

# What did you expect?
To verify successfully or be able to ignore this class (when other classes using it are verified).

# Which version of EqualsVerifier are you using?
3.4.2

# Please provide any additional information below.
The HashCode is an abstract class with hidden (private) subclasses (IntHashCode, BytesHashCode, etc). The abstract class implements the equals method in terms of abstract methods that are implemented in those specific subclasses.

**Comment by jqno** [comment]
So if I understand correctly, you want either to test the `HashCode` class, which you are unable to do because of the calls to abstract methods inside its `equals` and `hashCode` methods. Or you want to test `HashCode`'s concrete subclasses such as `IntHashCode` and `BytesHashCode` so you can safely skip testing `HashCode` itself, which you are unable to do because these classes are private.

Unfortunately, EqualsVerifier can't come up with implementations for the abstract methods by itself. It also can't work without actually calling `equals` and `hashCode`. So that leaves us in a complicated position.

I can see two possible workarounds. I don't know if either of them is acceptable for your use case.

1) Inside of your unit test class, you can create a custom subclass for `HashCode` that implements the required abstract methods in some easy way, and test that. That way you will know that `HashCode` is correct, assuming that its subclasses don't do anything strange.

2) Try to access the subclasses using reflection, something like this:
```
for (Class<?> cls : HashCode.class.getDeclaredClasses()) {
    EqualsVerifier.forClass(cls).verify();
}
```

**Comment by LukasGasior1** [comment]
Hi, thanks for quick reply.
I don't need to verify the HashCode class itself (that's a side quest ;) ). I trust (and see) that the implementation is correct. My main problem is that I have many classes that use it in their equals/hashCode methods that I'm unable to verify.
Example:
```

class Abc {
	private final HashCode hash;

	Abc(HashCode hash) {
		this.hash = hash;
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.hash);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj instanceof Asd) {
			Asd that = (Asd) obj;
			return Objects.equals(this.hash, that.hash);
		}
		return false;
	}
}

```
of course most of them have more fields (of different types) that are compared.

I guess what I need is a way to skip the recursive check for given set of classes (in my case just the HashCode).

**Comment by jqno** [comment]
Ah I suppose I misunderstood you then :). Thanks for the clarification.

Does it help to add `HashCode` as a prefab value? Something like this:

```
HashCode hc1 = ...;
HashCode hc2 = ...;
EqualsVerifier.forClass(Abc.class)
    .withPrefabValues(HashCode.class, hc1, hc2)
    .verify();
```

**Comment by LukasGasior1** [comment]
Yes! This is exactly what I needed. Thanks.
