### ISSUE TITLE
Improve CHANGELOG to include migration info for 3.1.x to 3.2.x

### ISSUE THREAD

**Issue by rbarbey** [jqno/equalsverifier#467]
Between 3.1.x and 3.2.x the code around `EqualsVerifierApi` changed a bit and updating might require some work. So a couple of lines in the README explaining these changes would be cool  (different package, more concrete types were introduced, `verify()` needs to be called on subtypes). Let me know if I can help.

Thank you!

**Comment by jqno** [comment]
Hi! Thanks for reaching out.

I try to make updates between minor versions (such as 3.1.x and 3.2.x) non-breaking so that you can upgrade without having to change any existing code. Only between major versions, things might break, so that's why I provide migration guides between major versions. The changelog should document everything that was added, fixed or changed in any given version.

So can you be more specific about the text you want to see in the readme? I'm afraid I don't understand the examples that you give.

Regards,
Jan

**Comment by rbarbey** [comment]
Hey @jqno !

Sure thing, here's a code example that hopefully illustrates my point a little bit better. In my code, I have a test like this:

```java
import nl.jqno.equalsverifier.EqualsVerifier;
import nl.jqno.equalsverifier.EqualsVerifierApi;
import nl.jqno.equalsverifier.Warning;

public class SomeTest
{
    @Test
    public void checkHashCodeAndEquals()
    {
        final EqualsVerifierApi<SomeObject> verifier = 
                EqualsVerifier
                    .forClass(SomeObject.class)
                    .usingGetClass()
                    .suppress(Warning.NONFINAL_FIELDS);
        verifier.verify();
    }
}
```

It compiles against equalsverifier version 3.1.9 but once I've updated to 3.2.x or later I essentially get two compilation errors:

1. The import `nl.jqno.equalsverifier.EqualsVerifierApi` cannot be resolved (yes, because it was moved to another package `nl.jqno.equalsverifier.api`)
2. After I've updated the import to accommodate for the new package, I get: The method `verify()` is undefined for the type `EqualsVerifierApi` (which has turned into an interface now) In order to fix that, I needed to use one of the implementations of `EqualsVerifierApi`, for example `SingleTypeEqualsVerifierApi`.

I think it would help others if there's some mention of this change in the `CHANGELOG.md` or some other place in the repo or on the website. I'm happy to draft something and create a pull request if that's fine with you.

**Comment by jqno** [comment]
Ahhh, I see what you mean now! Yes, please go ahead, if you create a PR for this, I'll happily merge it.

I guess I didn't add this because I never intended `EqualsVerifierApi` to be used as a variable, and as a result, it didn't cross my mind that it could be used that way. The idea is that you call `.verify()` directly, like this:

```
EqualsVerifier
    .forClass(SomeObject.class)
    .usingGetClass()
    .suppress(Warning.NONFINAL_FIELDS);
    .verify();
```

Or, if you want to re-use the configuration, one would use `EqualsVerifier.configure()` and go from there.

**Comment by jqno** [comment]
Are you still interested in creating this PR? Otherwise, I'll close the issue in a few days.

**Comment by jqno** [comment]
Closing now. Please feel free to re-open if you still want to do this.
