### ISSUE TITLE
Illegal reflective access to java.util.EventObject

### ISSUE THREAD

**Issue by zs3rg** [jqno/equalsverifier#526]
**Describe the bug**
Illegal reflective access by `nl.jqno.equalsverifier.internal.reflection.FieldModifier` to field `java.util.EventObject.source`

**To Reproduce**
- Extend `java.util.EventObject` class with few more fields that are used to check for equality of the extended class.
- Test for equality is successful, however _Illegal reflective access_ warning is thrown, both with and without `withPrefabValues()`.

**Code that triggers the behavior**

**Test class:**

```
import java.util.EventObject;

import org.junit.jupiter.api.Test;

import nl.jqno.equalsverifier.EqualsVerifier;

public class EnhancedEventObjectTest {

	@Test
	public void testEqualsAndHashCode() {
		EqualsVerifier.simple().forClass(EnhancedEventObject.class).verify();
	}

	@Test
	public void testEqualsAndHashCodeWithPrefabValues() {
		EqualsVerifier.simple()
				.forClass(EnhancedEventObject.class)
				.withPrefabValues(EventObject.class, new EventObject("1"), new EventObject("2"))
				.verify();
	}

}

```

**Class under test:**

```
import java.util.Objects;

public final class EnhancedEventObject extends java.util.EventObject {

	private static final long serialVersionUID = 4714333574716866618L;

	/**
	 * Used to distinguish the publisher of an event
	 */
	public enum Publisher {
		DATASOURCE_REGISTRY1,
		DATASOURCE_REGISTRY2,
		DATASOURCE_REGISTRY3
	}

	private final Publisher publisher;
	private final Object dataSource;

	public EnhancedEventObject(final Publisher publisher, final Object dataSource) {

		super(publisher);
		this.publisher = Objects.requireNonNull(publisher, "publisher is null");
		this.dataSource = Objects.requireNonNull(dataSource, "dataSource is null");
	}

	public Publisher getPublisher() {
		return publisher;
	}

	public Object getDataSource() {
		return dataSource;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((dataSource == null) ? 0 : dataSource.hashCode());
		result = prime * result + ((publisher == null) ? 0 : publisher.hashCode());
		return result;
		}

	@Override
	public boolean equals(final Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
				return false;
			}
			final EnhancedEventObject other = (EnhancedEventObject) obj;
			if (dataSource == null) {
				if (other.dataSource != null) {
					return false;
				}
			} else if (!dataSource.equals(other.dataSource)) {
				return false;
			}
			if (publisher != other.publisher) {
				return false;
			}
			return true;
		}

}


```

**Error message**
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by nl.jqno.equalsverifier.internal.reflection.FieldModifier (file:/C:/dev/_LIB/EQUALSVERIFIER/equalsverifier-3.7.jar) to field java.util.EventObject.source
WARNING: Please consider reporting this to the maintainers of nl.jqno.equalsverifier.internal.reflection.FieldModifier
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Expected behavior**
There should be no _Illegal reflective access_ warning thrown.

**Version**
3.7

**Additional context**
- Java 11
- JUnit 5
- Related to following discussion https://groups.google.com/g/equalsverifier/c/Q9HLQ3s2eIA

**Comment by hildaqwu** [comment]
@zs3rg hi, I would like to contribute to this issue, Could u plz assign this to me?

**Comment by jqno** [comment]
@hildaqwu I've assigned it to you. Please let me know if you need any help, I'd be happy to provide that!

**Comment by jqno** [comment]
@hildaqwu Are you still interested in contributing to this issue?

**Comment by WojciechZankowski** [comment]
@jqno I took a look at the issue and it doesn't seem to be a problem with ```prefabValues```. Actually the given example doesn't make much sense as far as I understand how prefabs concept works. 

```
EqualsVerifier.simple()
    .forClass(EnhancedEventObject.class)
    .withPrefabValues(EventObject.class, new EventObject("1"), new EventObject("2"))
    .verify();
```

```EventObject``` prefabs are already provided in ```JavaApiPrefabValues``` anyway. 

The problem comes from the fact that we are trying to set value through reflection to ```protected transient Object source``` in ```java.util.EventObject``` after initializing default empty ```EnhancedEventObject``` object. It fails the same way as the below example would:

```
EqualsVerifier.simple()
    .forClass(AtomicInteger.class)
    .verify();
```

I am not sure if any smart solution exists here. Probably some option would be to provide API to pass your own class instances against which internals can perform required checks?

**Comment by jqno** [comment]
I assumed it would be a matter of adding the prefab values, but you're right, and I didn't read it correctly. It's not the easy ticket I thought it was.

The important matter is that the class under test, `EnhancedEventObject`, extends `EventObject`. In order to instantiate a class, EqualsVerifier must also provide values for all of its fields, and it does so using reflection. Since `EventObject` lives in the `java.base` module, we can't simply do that. In this case, I can't provide a real solution, only workarounds:

- You can add `--illegal-access=permit` to the argument list when running tests. If you use Maven, it requires some configuration in the Surefire plugin, [as seen here](https://stackoverflow.com/questions/64920521/how-to-pass-add-opens-jdk-module-configuration-to-maven-test). Downside: you lose all reflection protection that the JDK provides in your unit tests.
- You can add `--add-opens java.base/java.util=ALL-UNNAMED` in the same way. Downside: now reflection into all classes in the `java.util` class will be possible for all unit tests. This is a safer option than the previous one but still leaves a lot open.

It would require significant changes to EqualsVerifier's internals in order to make this work, and unfortunately I don't have the time right now to do that, though I'm willing to help if you want to make a PR...

**Comment by jqno** [comment]
I'm closing this issue since it's become stale. We can always reopen it if needed.
