### ISSUE TITLE
forPackage/forClasses full API

### ISSUE THREAD

**Issue by xenoterracide** [jqno/equalsverifier#697]
**Is your feature request related to a problem? Please describe.**

I dislike writing a customized check for each jpa class

**Describe the solution you'd like**

    EqualsVerifier.forPackage("com.company").withOnlyTheseFields("id").verify()

**Describe alternatives you've considered**

just doing this for each class, or writing my own scanner, could also do this in a loop

    EqualsVerifier.forClass(ExceptionEntity::class.java).withOnlyTheseFields("id").verify()

**Additional context**

```
nl.jqno.equalsverifier:equalsverifier:3.10.1
```

**Comment by jqno** [comment]
That's a good idea!
I don't have a lot of spare time these days so unfortunately I can't promise I'll get to this soon. But I'm open for a PR :wink:

**Comment by xenoterracide** [comment]
If only my company would let me

**Comment by jqno** [comment]
I think I wasn't paying attention when I replied on this thread earlier, because such a feature already (almost) exists. You can do this:

```java
EqualsVerifier.configure()
        .suppress(...)
        .usingGetClass()
        .forPackage(...)
        .verify();
```

This won't let you specify certain things, including `.withOnlyTheseFields()` which is of course the one you asked for. The reason I left that out is that I thought it would be confusing to have it, because what if the specified field doesn't exist on some of the classes we're testing? I guess in a JPA context, you can assume `id` is always there, but that's an exceptional case that already [has a workaround](https://github.com/jqno/equalsverifier/issues/698#issuecomment-1249062627) that should work in this context -- can you check in your codebase and confirm or deny that?

**Comment by xenoterracide** [comment]
hmm... well per other ticket the `withOnlyTheseFields` doesn't work for me anyways. I also realize that `forPackage` won't because I do have other types that don't need equality in here. However, `forClasses` does.

What might be better though that would allow me to use `forPackage` is if I could do some kind of `forPackageWithType("my.package", AbstactClassOrInterface.class)` so that I could scan but check only things of that type.   Although maybe that should be a different ticket?

**Comment by jqno** [comment]
Glad it worked out! I agree, this feature request should be a new ticket, but I like the idea, so you're free to submit that. The same caveat applies though, I don't have a lot of time so I can't give you any timeframe. But at least you have a workaround now.

**Comment by xenoterracide** [comment]
lol, I ended up right back here... since removing `@EmbeddedId` `forClasses` won't work since it's missing this api. Any chance we could reopen?

**Comment by xenoterracide** [comment]
although this time I'm hitting significant fields. In the mean time I'm going to use parameterized junit

**Comment by jqno** [comment]
I think trying parameterized tests is a good idea, right tool for the job and everything... Please let me know how this works out for you. If it works well, I'll add something to the docs for those who run into similar issues! And if it doesn't work out, we can re-evaluate here.
