### ISSUE TITLE
Using forPackage runs on the test classes and not the src classes

### ISSUE THREAD

**Issue by justahuman1** [jqno/equalsverifier#727]
**Describe the bug**
When running `EqualsVerifier.forPackage(...)`, the verifier is checking all the classes within the `src/test/java/...` rather than `src/main/java`

**To Reproduce**
Add the `EqualsVerifier.forPackage()` in a `src/test/java/` directory where the `main` and `test` share the same package name.

**Code that triggers the behavior**
```
src/main/java
    com.hello.world
        HelloWorld.java
src/test/java
    com.hello.world
        HelloWorldTest.java
```
Adding a jUnit test method to `HelloWorldTest.java` with:

```java
@Test 
public void testEquals() {
    EqualsVerifier.forPackage("com.hello.world").verify();
}
```

**Error message**
```
EqualsVerifier found a problem in class com.hello.world.HelloWorldTest.
-> Equals is inherited directly from Object.
Suppress Warning.INHERITED_DIRECTLY_FROM_OBJECT to skip this check.
```
This error is because it's testing the test class and not the `src` class

**Expected behavior**
I expect the src classes to be tested.

**Version**
3.11

**Comment by justahuman1** [comment]
This may just be a bug with my codebase since I see no other mentions of this in Issues.

**Comment by jqno** [comment]
When scanning a package, EqualsVerifier picks up both the `src/main/` classes and the `src/test` classes. However, it filters out every class whose name ends in `Test`, so it should just ignore any test classes.

Maybe as a sanity check, can you see what happens if you introduce an intentional error in your `HelloWorld.java`'s equals method? Does it give an error there as well?

Also, if the problem persists, can you maybe make a small reproducer? Because this is clearly incorrect behaviour for EqualsVerifier.

**Comment by jqno** [comment]
Any updates on this?

**Comment by justahuman1** [comment]
Hi, yes, verified that this bug was present due to the naming of our test classes. Apologies for the false positive. Closing the issue. Thanks for the hard work on this library!

**Comment by jqno** [comment]
Thanks for the kind words! Don't worry about the false positive, I'm glad you were able to resolve it.
