### ISSUE TITLE
"Recursive datastructure" warning even when the recursive field is ignored

### ISSUE THREAD

**Issue by armandino** [jqno/equalsverifier#865]
**Describe the bug**
When using EV with a class that references itself, the "Recursive datastructure" warning is produced even if the self-referencing field is ignored using the `withIgnoredFields()` method.

**To Reproduce**
```java
class Example {
    String value;
    Example example;

    @Override
    public boolean equals(final Object o) {
        if (this == o) return true;
        if (!(o instanceof Example)) return false;
        return Objects.equals(value, ((Example) o).value);
    }

    @Override
    public int hashCode() {
        return value == null ? 0 : value.hashCode();
    }
}


EqualsVerifier.forClass(Example.class)
    .withIgnoredFields("example")
    .verify();
```

**Error message**
```
-> Recursive datastructure.
Add prefab values for one of the following types: Example.
```

**Expected behavior**
Since the recursive field is ignored, EV should not produce the warning.

**Version**
`3.15.2`

**Additional context**

**Comment by jqno** [comment]
Ignoring a field refers to ignoring it in the check if equals is correct. However, before EqualsVerifier can do that, it needs to instantiate an object of the class you're testing, and in this phase, the field can't be ignored, unfortunately. You'll have to call `.withPrefabalues` for `Example.class`, even if that seems weird because it's the class you're testing.

I'm trying to find ways around this, but so far I haven't found any.

**Comment by armandino** [comment]
Thanks for the background on this. Yes, I've been using `withPrefabValues` in such cases. I think this would be a nice to have as ignoring a field is more convenient than creating prefab values, but no worries if it's not feasible to implement.

**Comment by jqno** [comment]
In this particular case, you still have to do both: the prefab value for instantiating, and ignore to keep EqualsVerifier from checking equals with it.

But yeah, I agree. I'd like to get rid of prefab values altogether.
