### ISSUE TITLE
Field backtrace of type java.lang.Object is not accessible via the Java Module System

### ISSUE THREAD

**Issue by olegs1993** [jqno/equalsverifier#967]
### Describe the bug

Hello team,
could you please suggest any workaround with this error please?
![image](https://github.com/jqno/equalsverifier/assets/23138783/0fdabf10-8ac4-4fd5-9d49-25fd8e092528)

there is a simple exception class with equals and hashcode
when try to test via EqualsVerifier it throws:
java.lang.AssertionError: EqualsVerifier found a problem in class AccessPermissionException.
-> Field backtrace of type java.lang.Object is not accessible via the Java Module System.
Consider opening the module that contains it, or add prefab values for type java.lang.Object.

the method .withPrefabValues(Object.class, new Object(), new Object()) also does not work for me

is it possible to test such case at all? thanks in advance

**Comment by jqno** [comment]
This happens because RuntimeException is in the java.lang module, and even if you don't use modules yourself, the JVM enforces it. The only way to go forward is if you open the java.lang module, as the error message suggests. Adding prefab values unfortunately won't help in this particular situation.

You can do that by adding the command-line flag `--add-opens java.base/java.lang=ALL-UNNAMED` to the call that runs your tests. If you're using Maven, it's a configuration option in the surefire plugin; if you're using Gradle (or something else), you'll have to find out yourself how to do that, because I don't have enough experience with those.

BTW, next time, can you please copy/paste the actual code into the text box? It's impossible to copy/paste from a screenshot, so I had to re-type everything to reproduce your issue...

**Comment by olegs1993** [comment]
HI @jqno, thanks for your response, so adding this flag is the only one option we have to fix the issue, correct?
I am sorry, yes, next time will add code sample :)

**Comment by jqno** [comment]
Yes, when you extend a class from the java.base module that has fields of its own, it's unfortunately the only option.
