### ISSUE TITLE
[Bug] Runing JOSM Tests on MacOS causes an "Illegal reflective access by nl.jqno.equalsverifier.internal.reflection.FieldModifier"

### ISSUE THREAD

**Issue by stoecker** [jqno/equalsverifier#988]
### Describe the bug

When running JOSM CI Test all of the Java versions 11,17,21,22 issue following warning:
```
[junitlauncher] Running org.openstreetmap.josm.data.osm.search.SearchCompilerTest
[junitlauncher] WARNING: An illegal reflective access operation has occurred
[junitlauncher] WARNING: Illegal reflective access by nl.jqno.equalsverifier.internal.reflection.FieldModifier (file:/Users/runner/.ivy2/cache/nl.jqno.equalsverifier/equalsverifier/jars/equalsverifier-3.16.1.jar) to field javax.swing.AbstractAction.enabled
[junitlauncher] WARNING: Please consider reporting this to the maintainers of nl.jqno.equalsverifier.internal.reflection.FieldModifier
[junitlauncher] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[junitlauncher] WARNING: All illegal access operations will be denied in a future release
[junitlauncher] Tests run: 92, Failures: 0, Aborted: 0, Skipped: 0, Time elapsed: 3.857 sec
```
See https://github.com/JOSM/josm/actions/runs/10355446976/job/28663112515

I assume it should be possible to reproduce this by cloning the JOSM repository.

### Steps to reproduce

Run test target of JOSM repo.

### Error message and version number

See description

### Code: EqualsVerifier invocation

See repo

### Code: class under test

See description

**Comment by jqno** [comment]
I see it happens when accessing a field in a Swing AbstractAction, so one of your classes probably has AbstractAction as one of its fields, right? EqualsVerifier doesn't have a built-in prefab value for that, so it will try to instantiate an AbstractAction using reflection, which is forbidden for JDK modules, and that's the error you see.

You have two options: either add prefab values for AbstractAction, or open the module so EqualsVerifier gets permission to reflect into it. See https://jqno.nl/equalsverifier/manual/jpms/ if you want to know more about this.
